import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import richy from '../public/IMG_2932.jpg';
import languages from '../public/language.png';
import software from '../public/software.png';
import hardware from '../public/hardware.png';
import {useState} from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Richel Oliver Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/IMG_6249.jpg" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-2xl font-burtons">Nedril</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill  onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8" href='/Resume_New.pdf'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 dark:text-white">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white">Richel Oliver</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Software Engineer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              Hello, my name is Richel Oliver and I am currently a Senior at Florida International University majoring in Computer Engineering graduating on August of 2023.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.instagram.com/richyned_/"><AiFillInstagram /></a>
            <a href="https://www.linkedin.com/in/richel-oliver-1367981b2/"><AiFillLinkedin /></a>
            <a href="https://github.com/Richel7"><AiFillGithub /></a>
            

          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={richy} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
            As a student passionate about <span className="text-teal-500"> software engineering, </span> I am constantly intrigued by the innovative <span className="text-teal-500"> technology </span> that powers the world around us. I am fascinated by the intricate details that go into creating <span className="text-teal-500"> software applications </span> that make our lives easier and more efficient. I am dedicated to honing my <span className="text-teal-500"> programming skills </span> and staying up-to-date with the latest developments in the field. I find joy in <span className="text-teal-500"> problem-solving,</span> and I am eager to apply my knowledge to create innovative solutions. <span className="text-teal-500"> My goal </span> is to be a part of a dynamic team that develops groundbreaking software products and changes the world for the better.
            </p>
          </div>

        </section>
        
        <section>

          <div className="lg:flex gap-10 dark:text-white">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-white">
              <Image src={languages} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Programming Languages
              </h3>
              <p className="py-1 dark:text-white">
                
              </p>
              <p className="text-gray-800 py-1 dark:text-white">Python</p>
              <p className="text-gray-800 py-1 dark:text-white">C/C++</p>
              <p className="text-gray-800 py-1 dark:text-white">Java</p>
              <p className="text-gray-800 py-1 dark:text-white">HTML/CSS</p>
              <p className="text-gray-800 py-1 dark:text-white">JavaScrip</p>
              <p className="text-gray-800 py-1 dark:text-white">VHDL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={software} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Software
              </h3>
              <p className="py-1">
                
              </p>
              <p className="text-gray-800 py-1 dark:text-white">Git/GitHub</p>
              <p className="text-gray-800 py-1 dark:text-white">Linux/Unix</p>
              <p className="text-gray-800 py-1 dark:text-white">VSCode</p>
              <p className="text-gray-800 py-1 dark:text-white">CodeBlocks</p>
              <p className="text-gray-800 py-1 dark:text-white">Xilinx Vivado</p>
              <p className="text-gray-800 py-1 dark:text-white">IntelliJ IDEA</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-white">
              <Image src={hardware} width={100} height={100}/>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Hardware
              </h3>
              <p className="py-1">
                
              </p>
              <p className="text-gray-800 py-1 dark:text-white">Arduino</p>
              <p className="text-gray-800 py-1 dark:text-white">Rasberry Pi</p>
              <p className="text-gray-800 py-1 dark:text-white">NodeMCU</p>
              <p className="text-gray-800 py-1 dark:text-white">Beagle Bone</p>
            </div>
          </div>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Contact Information</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Phone # : 
              <span className="text-teal-500"> 786-816-1124 </span>
              <br></br>Personal Email: <span className="text-teal-500"> richeloliver@gmail.com </span>
              <br></br>Discord: <span className="text-teal-500"> Nedril. #8982 </span>
            </p>
          </div>
        </section>
      </main>
    </div>

  );
}
